AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  DynamoDBPrac

  Sample SAM Template for DynamoDBPrac

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.App::handleRequest
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          TABLE_NAME: Student  # Ensure this matches the manually created table
#        Policies:
#          - DynamoDBCrudPolicy:
#              TableName: Student
      Events:
        # Event to fetch student by ID
        GetStudentById:
          Type: Api
          Properties:
            Path: /students/{id}  # Path with {id} for fetching student by ID
            Method: get

        # Event to fetch all students
        UpdateStudentById:
          Type: Api
          Properties:
            Path: /students/{id}  # Path to fetch all students
            Method: put

        # Event to add a new student
        AddStudent:
          Type: Api
          Properties:
            Path: /students  # Path to add a new student
            Method: post

        # Event to delete a student by ID
        DeleteStudent:
          Type: Api
          Properties:
            Path: /students/{id}  # Path to delete a student by ID
            Method: delete
#        HelloWorld:
#          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
#          Properties:
#            Path: /hello
#            Method: get
#        GetStudents:
#          Type: Api
#          Properties:
#            Path: /getStudentDetails
#            Method: get
#        AddStudents:
#          Type: Api
#          Properties:
#            Path: /addStudentDetails
#            Method: post



Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
